package com.unicauca.figures.domain.presentation;

import com.unicauca.figures.domain.model.Triangle;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

public class GUITriangle extends javax.swing.JFrame {

    private Triangle triangle;
    public GUITriangle() {
        initComponents();
        triangle = new Triangle(1, 1, 1, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pnlForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBase = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSide2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSide3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPerimeter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("T R I A N G L E");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculate);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pnlForm.setLayout(new java.awt.GridLayout(6, 2));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Height:");
        pnlForm.add(jLabel2);
        pnlForm.add(txtHeight);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Base");
        pnlForm.add(jLabel4);
        pnlForm.add(txtBase);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Side 2");
        pnlForm.add(jLabel3);
        pnlForm.add(txtSide2);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Side 3");
        pnlForm.add(jLabel5);
        pnlForm.add(txtSide3);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Area");
        pnlForm.add(jLabel6);

        lblArea.setForeground(new java.awt.Color(0, 204, 204));
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArea.setText("-");
        pnlForm.add(lblArea);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Perimeter");
        pnlForm.add(jLabel8);

        lblPerimeter.setForeground(new java.awt.Color(204, 0, 0));
        lblPerimeter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerimeter.setText("-");
        pnlForm.add(lblPerimeter);

        getContentPane().add(pnlForm, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try
        {            
            if((txtHeight.getText().isEmpty()) && (txtBase.getText().isEmpty()) && (txtSide2.getText().isEmpty()) && (txtSide3.getText().isEmpty()))
            {
                JOptionPane.showMessageDialog(this, "No deben quedar espacios en blanco.", "Error", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                if((Double.parseDouble(txtHeight.getText()) > 0) && (Double.parseDouble(txtBase.getText()) > 0) && (Double.parseDouble(txtSide2.getText()) > 0) && (Double.parseDouble(txtSide3.getText()) > 0))
                {
                    triangle.setHeight(Double.parseDouble(txtHeight.getText()));
                    triangle.setBase(Double.parseDouble(txtBase.getText()));
                    triangle.setSide2(Double.parseDouble(txtSide2.getText()));
                    triangle.setSide3(Double.parseDouble(txtSide3.getText()));
                    lblArea.setText("" + triangle.calculateArea());
                    lblPerimeter.setText("" + triangle.calculatePerimeter());
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Los valores no pueden ser cero ni un valor negativo.", "Error", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Ingrese un valor valido.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITriangle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblPerimeter;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtSide2;
    private javax.swing.JTextField txtSide3;
    // End of variables declaration//GEN-END:variables
}
